PHASE_1_LABELS = ["Airway wall thickening",
                  "Atelectasis",
                  "Consolidation",
                  "Emphysema",
                  "Enlarged cardiac silhouette",
                  "Fibrosis",
                  "Fracture",
                  "Groundglass opacity",
                  "Mass",
                  "Nodule",
                  "Pleural effusion",
                  "Pleural thickening",
                  "Pneumothorax",
                  "Pulmonary edema",
                  "Wide mediastinum"]

PHASE_2_3_LABELS = ["Abnormal mediastinal contour",
                    "Acute fracture",
                    "Atelectasis",
                    "Consolidation",
                    "Enlarged cardiac silhouette",
                    "Enlarged hilum",
                    "Groundglass opacity",
                    "Hiatal hernia",
                    "High lung volume / emphysema, Interstitial lung disease",
                    "Lung nodule or mass",
                    "Pleural abnormality",
                    "Pneumothorax",
                    "Pulmonary edema"]